### ISSUE TITLE
ESP8266 gateway with 2 sensors (2 relay) reconnects to OPENHAB2 after long time

### ISSUE THREAD

**Issue by lucarui** [tobof/openhab2-addons#122]
Hello,
I noticed that my ESP8266 gateway (with 2 relay used to switch on 2 different lights), when connection with controller (openhab2) is lost, it needs at least 3 minutes to reconnect to it.
It could be an issue or a configuration that I don't know?

Thanks.

**Comment by andreacioni** [comment]
Hi @lucarui,

have you already set the `networkSanCheckInterval` parameter in the bridge configuration? As you can see in the [wiki](https://github.com/tobof/openhab2-addons/wiki/Configuration#common-parameters-for-all-gateway-types) you can give it the value you want (in minutes); the default value is, in fact, 3 minutes.

Hope this help  :wink:

**Comment by andreacioni** [comment]
The problem of the long delay can also be related to the `networkSanCheckConnectionFailAttempts=3` because the NetworkSanityChecker will try every one minute (for a maximum of 3 times) to check if the connection is recovered. Try to set that parameter to 1 (or 0, I don't remember it precisely) and test again.
