### ISSUE TITLE
Binding issue related to recent updates on Smarthome API

### ISSUE THREAD

**Issue by andreacioni** [tobof/openhab2-addons#40]
Hi Tim!

Due to the recent issue on the binding please note that conversation about new API lifecycle https://github.com/eclipse/smarthome/pull/2087. 

I think that one try you could do is to put event listener registration inside MySensorsThingHandler.initialize(). This should allow you to avoid the problem. 
I've tested this on my refactoring (I hope to PR it early 😉  ) but should work also in your version.

Let me know!

**Comment by andreacioni** [comment]
Take a look [here](https://github.com/andreacioni/openhab2-addons/blob/MySensors/addons/binding/org.openhab.binding.mysensors/src/main/java/org/openhab/binding/mysensors/internal/handler/MySensorsThingHandler.java#L73)

**Comment by tobof** [comment]
Hey Andrea!

Thank you for your input, I've come to the same conclusion. One additional change is, that the ThingStatus has set to ONLINE on init, because otherwise the thing will update although it is OFFLINE. ;-) 

It also fixes the problem with autodiscovery, which is reasonable, because they never come ONLINE and register the EventListener till the bridge changes its status.

I'll do some further testing and push the changes.

**Comment by tobof** [comment]
Problem is solved. 

Bindings from now on are not backward compatible due to the changes in the OH2 API.
