### ISSUE TITLE
S_LIGHT_LEVEL & V_LEVEL

### ISSUE THREAD

**Issue by Fejitatete** [tobof/openhab2-addons#51]
Since the last update, the V_LEVEL sensor is not recognize properly (OH think it is an actuator may be ?) : 

`00:55:43.190 [DEBUG] [rs.internal.protocol.MySensorsReader] - 0;255;3;0;9;TSF:MSG:READ,101-101-0,s=2,c=1,t=37,pt=7,l=5,sg=0:246
00:55:43.196 [DEBUG] [rs.internal.protocol.MySensorsReader] - 0;255;3;0;9;TSF:MSG:ACK REQ
00:55:43.211 [DEBUG] [rs.internal.protocol.MySensorsReader] - 0;255;3;0;9;Will not sign message for destination 101 as it does not require it
00:55:43.223 [DEBUG] [rs.internal.protocol.MySensorsReader] - 0;255;3;0;9;TSF:MSG:SEND,0-0-101-101,s=2,c=1,t=37,pt=7,l=5,sg=0,ft=0,st=OK:246
00:55:43.235 [DEBUG] [rs.internal.protocol.MySensorsReader] - 101;2;1;0;37;246
00:55:43.247 [ERROR] [rs.internal.protocol.MySensorsReader] - (java.lang.IllegalStateException: Could not update state, because callback is missing) on reading from connection, message: class org.openhab.binding.mysensors.internal.protocol.serial.MySensorsSerialReader
`

OH version : SNAPSHOT BUILD N°710
MYSensorsBinding version : 2.0.0 SNAPSHOT

**Comment by tobof** [comment]
Hey @Fejitatete ,
thank you for reporting!

I've updated yesterday too.

After examination of the logs, I see:

1) `2017-01-10 19:59:32.330 [INFO ] [el.core.internal.ModelRepositoryImpl] - Refreshing model 'demo.things'`

2) `2017-01-10 19:59:32.650 [ERROR] [ore.thing.internal.ThingRegistryImpl] - Could not inform the ThingTracker 'org.eclipse.smarthome.core.thing.internal.ThingManager@25cf3142' about the 'THING_UPDATED' event!
java.lang.NullPointerException
        at org.eclipse.smarthome.core.thing.internal.ThingManager.thingUpdated(ThingManager.java:542)[104:org.eclipse.smarthome.core.thing:0.9.0.201612221226]
        at org.eclipse.smarthome.core.thing.internal.ThingRegistryImpl.notifyTrackers(ThingRegistryImpl.java:227)[104:org.eclipse.smarthome.core.thing:0.9.0.201612221226]
        at org.eclipse.smarthome.core.thing.internal.ThingRegistryImpl.notifyListenersAboutUpdatedElement(ThingRegistryImpl.java:150)[104:org.eclipse.smarthome.core.thing:0.9.0.201612221226]`

3) `2017-01-10 19:59:44.245 [DEBUG] [rs.internal.protocol.MySensorsReader] - 107;3;1;0;1;47.5
2017-01-10 19:59:44.245 [ERROR] [rs.internal.protocol.MySensorsReader] - (java.lang.IllegalStateException: Could not update state, because callback is missing) on reading from connection, message: class org.openhab.binding.mysensors.internal.protocol.serial.MySensorsSerialReader`

Could you please verify this in your openhab.log?

This does not depend on S_LIGHT_LEVEL or V_LEVEL.

Issue: https://github.com/eclipse/smarthome/issues/2733
Fix / PR: https://github.com/eclipse/smarthome/pull/2739

**Comment by Fejitatete** [comment]
I'll take a look this evening :).

**Comment by Fejitatete** [comment]
That's right, it does not depend on S_LIGHT_LEVEL or V_LEVEL. But a restart of the binding or OH2 don't solve the problem. It's a node with four childs and only the item linked with the third channel (CHILD_ID = 2) is not updated. Other thing weird, in the things conf pannel, there is this options :
![screenshotoh2](https://cloud.githubusercontent.com/assets/6900432/21865899/470b8178-d848-11e6-9901-b546b8bbc727.png)

Is that normal ?

Regards,

Feji.

**Comment by tobof** [comment]
@Fejitatete Found the problem. V_LEVEL was not mapped to S_LIGHT_LEVEL.

Thank you for reporting!
